version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - UPLOAD_DIR=/app/uploads
      - PROCESSED_DIR=/app/processed
      - LOG_LEVEL=INFO
      - WHISPER_MODEL=base
      - TRANSLATION_MODEL=facebook/mbart-large-50-many-to-many-mmt
      - TTS_MODEL=tts_models/es/css10/vits
      - MAX_FILE_SIZE=100000000
      - ALLOWED_VIDEO_TYPES=video/mp4,video/avi,video/mov,video/mkv
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    restart: unless-stopped

  celery:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
      - ./temp:/app/temp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery
    command: celery -A tasks flower --port=5555

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 