version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./output:/app/output
      - ./temp:/app/temp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
      - ./temp:/app/temp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery
    command: celery -A tasks flower --port=5555

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 